_target_: feature_based_propensities_for_ULTR.simulation.simulator.NeuralRanker
model_type: plackett_luce
policy_strength: ${policy_strength}
random_state: ${random_state}
training_data_percentage: 10.0
